# Pandas
---

In [2]:
import pandas as pd

### Series

In [13]:
"""Series""" #대문자임

pd_list = pd.Series([5000,6000,6500,7000], index=["아메리카노", "카페라떼", "카페모카", "카푸치노"])
print(pd_list)

아메리카노    5000
카페라떼     6000
카페모카     6500
카푸치노     7000
dtype: int64


In [14]:
#스리즈 요소 따로 뽑기(잘안씀)

print("스리즈의 값 : ", pd_list.values)
print("스리즈의 인덱스 값 :", pd_list.index)

스리즈의 값 :  [5000 6000 6500 7000]
스리즈의 인덱스 값 : Index(['아메리카노', '카페라떼', '카페모카', '카푸치노'], dtype='object')


### DataFrame

In [ ]:
values = [[1,2,3], [4,5,6], [7,8,9]] #[ 한행씩, 한행씩, 한행씩 ]
index = ['a','b','c']
columns = ['A','B','C']

pd_dataframe = pd.DataFrame(data=values, index=index, columns=columns)
print(pd_dataframe)

In [16]:
_value = [[1,2,3], [4,5,6], [7,8,9]]
_index = ['a','b','c']
_columns = ['A','B','C']

pd_df = pd.DataFrame(_value, index=_index, columns=_columns)
print(pd_df)

   A  B  C
a  1  2  3
b  4  5  6
c  7  8  9


In [18]:
print("데이터프레임의 값 : ", pd_df.values)
print("데이터프레임의 인덱스 값 : ", pd_df.index)
print("데이터프레임의 컬럼 값 :", pd_df.columns)

데이터프레임의 값 :  [[1 2 3]
 [4 5 6]
 [7 8 9]]
데이터프레임의 인덱스 값 :  Index(['a', 'b', 'c'], dtype='object')
데이터프레임의 컬럼 값 : Index(['A', 'B', 'C'], dtype='object')


In [29]:
"""딕셔너리 데이터를 데이터프레임으로"""

_values = {
    "name": ["A", "B", "C"],
    "age": [20, 30, 40],
    "phone": ["01011111111", "01022222222", "01033333333"]
}
_index = ['행1', '행2', '행3']

pd_df2 = pd.DataFrame(_values, index=_index)
pd_df2


name  age        phone
행1    A   20  01011111111
행2    B   30  01022222222
행3    C   40  01033333333

### 출력방법 - head(),tail(),["행이름"]

In [32]:
print(pd_df2.head(2))
print(pd_df2.tail(2))
print(pd_df2["name"])


   name  age        phone
행1    A   20  01011111111
행2    B   30  01022222222
   name  age        phone
행2    B   30  01022222222
행3    C   40  01033333333
행1    A
행2    B
행3    C
Name: name, dtype: object


---

## CSV불러오기

- 경로 지정
  > 절대 경로 - 절대적인 주소 (예: url주소, c:\users\test/txt, 도로명주소)
  <br>
  > 상대 경로 - 작업중인 환경에서 현재, 상위, 하위 폴더를 경로로 지정
  
<br>

- './' - **현재** 작업중인 디렉토리
- '../' - 상위 디렉토리 이동
- './폴더명/' - 하위 디렉토리 이동

- 절대경로는 웹API같이 경로가 변하지 않는 경로의 경우 사용
- 상대경로는 사용자간에 파일을 공유할 때 절대경로는 계속 바꿔야하는 번거로움이 있기에 상대경로 사용. 사용할 파일을 하나의 Data폴더에 넣어 사용.

In [4]:
csv_df = pd.read_csv("../csv/example.csv")   #절대경로
csv_df

Name  Gender          Phone
0    A    male  010-1234-5678
1    B  female  010-1234-5679
2    C    male  010-1234-5680
3    D  female  010-1234-5681
4    E    male  010-1234-5682
5    F  female  010-1234-5683
6    G    male  010-1234-5684
7    H  female  010-1234-5685
8    I    male  010-1234-5686
9    J  female  010-1234-5687

---

# Numpy

- ndarray/np.array(다차원 행렬자료 구조)를 통해 선형대수계산(행렬,벡터)에서 사용
- pd의 DataFrame과 다르게 array에선  [ ] 대괄호가 하나 더 사용된다.

> np_array_1 = np.array([1,2,3,4]) <- value를 넣을 땐 [,]<br>
> full_array = np.full((4,4), 3) <- 행렬 size에 대한 값은 (,)

In [6]:
import numpy as np

In [8]:
np_array_1 = np.array([1,2,3,4])
print(np_array_1)
print(type(np_array_1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [10]:
np_array_2 = np.array([[1,2,3], [4,5,6]])
print(np_array_2)

[[1 2 3]
 [4 5 6]]


In [13]:
print(np_array_2.ndim)
print(np_array_2.shape)


2
(2, 3)


In [19]:
# 0행렬
zero_array = np.zeros((3,4))
print(zero_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
# 1행렬
one_array = np.ones((3, 3))
print(one_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [21]:
# full행렬
full_array = np.full((4,4), 3)      #행렬단위는 ()가 있어야함.
print(full_array)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [22]:
# 단위행렬
eye_array = np.eye(5)
print(eye_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [25]:
# random
arrange_array = np.arange(10)   #10개 생성
print(arrange_array)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
# reshape, size조정
reshape_array = arrange_array.reshape((2,5))    #원소의 갯수가 딱 맞아야한다.
print(reshape_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## 행렬 연산

In [30]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [37]:
"""사칙연산"""

print(x+y)
print(np.add(x,y))  #위와 같음

print(x-y)
print(np.subtract(x,y))

print(x*y)
print(np.multiply(x,y))

print(x/y)
print(np.divide(x,y))

[5 7 9]
[5 7 9]
[-3 -3 -3]
[-3 -3 -3]
[ 4 10 18]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0.25 0.4  0.5 ]


In [40]:
"""행렬곱(@,dot)"""

x2 = np.array([[1,2],[3,4]])
y2 = np.array([[5,6],[7,8]])

In [41]:
print(x2 @ y2)
print(np.dot(x2,y2))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
